---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels: 
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}