apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
 
  labels:
    app: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - image: myregistry:5000/todos-api
          name: todos-api
          ports:
          - containerPort: 8082
          env:
          - name: JWT_SECRET
            value: myfancysecret
          - name: TODO_API_PORT
            value: "8082"
          - name: REDIS_HOST
            value: lab1
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_CHANNEL
            value: log_channel
          - name: ZIPKIN_HOST
            value: lab1
          - name: ZIPKIN_PORT
            value: "9411"
          - name: ZIPKIN_URL
            value: http://lab1:9411/api/v2/spans
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        fsGroup: 0
      imagePullSecrets:
      - name: dockerhub-image-pull-secret