apiVersion: v1
kind: Service
metadata:
  labels: 
    app: log-message-processor
  name: log-message-processor
  namespace: microservices-example
spec:
  ports:
  - port: 8083
  selector:
    app: log-message-processor