kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
  namespace: microservices-example
data:
  nginx.conf: | 
    server {
      listen       80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      location /login {
          proxy_pass http://auth-api:8081;
      }

      location /todos {
          proxy_pass http://todos-api:8082;
      }

      location /zipkin {
          proxy_pass http://192.168.0.101:9411;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
        } 
